import streamlit as st
import numpy as np
from PIL import Image
import tensorflow as tf
tflite = tf.lite

# Load TFLite model
interpreter = tflite.Interpreter(model_path='ai_image_detector.tflite')
interpreter.allocate_tensors()

# Get input and output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

IMG_SIZE = 64

# Page config
st.set_page_config(
    page_title="AI Image Detector",
    page_icon="🔍",
    layout="centered"
)

# Header
st.markdown("""
    <h1 style='text-align: center; color: #4F8BF9;'>🔍 AI Image Detector</h1>
    <p style='text-align: center; color: gray; font-size: 18px;'>
        Upload an image and find out if it was generated by AI or taken by a real camera.
    </p>
    <hr>
""", unsafe_allow_html=True)

# Upload
uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('RGB')
    st.image(image, caption="Uploaded Image", use_column_width=True)

    # Preprocess
    img = image.resize((IMG_SIZE, IMG_SIZE))
    img_array = np.array(img, dtype=np.float32) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Predict
    with st.spinner("Analyzing image..."):
        interpreter.set_tensor(input_details[0]['index'], img_array)
        interpreter.invoke()
        prediction = interpreter.get_tensor(output_details[0]['index'])[0][0]

    # Result
    st.markdown("<hr>", unsafe_allow_html=True)

    if prediction > 0.5:
        confidence = prediction * 100
        st.markdown(f"""
            <div style='background-color:#e6f4ea; padding:20px; border-radius:10px; text-align:center;'>
                <h2 style='color:#2e7d32;'>✅ Real Image</h2>
                <p style='font-size:18px; color:#2e7d32;'>Confidence: <b>{confidence:.1f}%</b></p>
            </div>
        """, unsafe_allow_html=True)
    else:
        confidence = (1 - prediction) * 100
        st.markdown(f"""
            <div style='background-color:#fdecea; padding:20px; border-radius:10px; text-align:center;'>
                <h2 style='color:#c62828;'>🤖 AI Generated</h2>
                <p style='font-size:18px; color:#c62828;'>Confidence: <b>{confidence:.1f}%</b></p>
            </div>
        """, unsafe_allow_html=True)

    # Progress bar
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown("**Prediction confidence:**")
    st.progress(float(prediction))
    st.caption("Real ◀──────────────▶ AI Generated")
    st.write(f"Raw prediction value: {prediction}")

# Footer
st.markdown("""
    <hr>
    <p style='text-align:center; color:gray; font-size:13px;'>
        Built with TFLite + Streamlit · CIFAKE Dataset · CNN Classifier
    </p>
""", unsafe_allow_html=True)